### ISSUE TITLE
Pre-train model

### ISSUE THREAD

**Issue by Phelan164** [herobd/Visual-Template-Free-Form-Parsing#1]
Hi guys,

Could you share your pre-trainer model?

Thanks!

**Comment by lamhoangtung** [comment]
Hi :P, do you guys have plan to release the Pretrained Model. Thanks :P

**Comment by AruniRC** [comment]
Just giving another bump to this issue. Pre-trained models would be great!

**Comment by herobd** [comment]
Sorry! I though I had added them to a release, but I guess I forgot. There now downloadable in the release https://github.com/herobd/Visual-Template-Free-Form-Parsing/releases/tag/w1.0
