### ISSUE TITLE
Testing the model

### ISSUE THREAD

**Issue by pranjal0000** [herobd/Visual-Template-Free-Form-Parsing#2]
Rather than evaluating over the entire dataset as mentioned in the README, can you please explain how we can test the model, from a given checkpoint, on a single image?

**Comment by herobd** [comment]
There isn't code for running on a single image sorry. However, it should be pretty easy to do.

`eval.py` should show you how to load the model:
`checkpoint = torch.load(resume_path, map_location=lambda storage, location: storage)`
`model = eval(config['arch'])(checkpoint['config']['model'])`
`model.load_state_dict(checkpoint['state_dict'])`

Then you just need to preprocess the image as seen in `datasets/graph_pair.py`:
`np_img = cv2.imread(imagePath, 1 if self.color else 0)`
`np_img = cv2.resize(np_img,new_size)` (just be sure the size in roughly in the range it's been trained to see)
`img = np_img.transpose([2,0,1])[None,...]`
`img = img.astype(np.float32)`
`img = torch.from_numpy(img)`
`img = 1.0 - img / 128.0`

Then just run the image through the model:
`bbPred, _, relPred, relIndexes, bbOut = model(img)`

**Comment by herobd** [comment]
There is now a script for this. See `run.py`
