### ISSUE TITLE
How to test folder of files on pre trained network

### ISSUE THREAD

**Issue by its-charan-here** [herobd/Visual-Template-Free-Form-Parsing#6]
I want to test the pretrained neural Network weights on my testing dataset. Can someone guide me on how to do that?
and I am still unsure how to proceed with training with the given set of files. 

and moreover, I am facing this issue while running `python eval.py -n 0 -T -a data_loader=special_dataset=simple`

This is the output :
`
Traceback (most recent call last):
  File "eval.py", line 21, in <module>
    from model import *
  File "E:\Yolo paper\Visual-Template-Free-Form-Parsing\model\__init__.py", line 2, in <module>
    from model.pairing_graph import PairingGraph
  File "E:\Yolo paper\Visual-Template-Free-Form-Parsing\model\pairing_graph.py", line 25, in <module>
    from model.roi_align import ROIAlign as RoIAlign
  File "E:\Yolo paper\Visual-Template-Free-Form-Parsing\model\roi_align.py", line 9, in <module>
    from model import _C
`

and this is the Error:

`ImportError: cannot import name '_C' from partially initialized module 'model' (most likely due to a circular import)`

How should I remove this error?

**Comment by herobd** [comment]
The error is coming from something not being built right with Facebook's RoIAlign implementation. I've replaced that with the torchvision one, so as long as you have the right version of Pytorch you should be good.

You can use my dataset object, but it assumes a GT json that accompanies every image and a json pointing to all the images in the dataset (`train_valid_test_split.json`). If you don't have the GT, you'll have to write your own code to run it on your data. (see https://github.com/herobd/Visual-Template-Free-Form-Parsing/issues/2)

What is your question about training on the provided data? The two training commands in the README should do it once you've gotten the data.

**Comment by its-charan-here** [comment]
> The error is coming from something not being built right with Facebook's RoIAlign implementation. I've replaced that with the torchvision one, so as long as you have the right version of Pytorch you should be good.
> 
> You can use my dataset object, but it assumes a GT json that accompanies every image and a json pointing to all the images in the dataset (`train_valid_test_split.json`). If you don't have the GT, you'll have to write your own code to run it on your data. (see #2)
> 
> What is your question about training on the provided data? The two training commands in the README should do it once you've gotten the data.

Thank you for your response,

I have GCC version 9 and Cuda 10.1 with PyTorch version 1.4 and it is throwing 
this error :
`
C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\bin\\nvcc.exe' failed with exit status 1
`
while executing the `python setup.py build develop`

**Comment by herobd** [comment]
Oh, you shouldn't need to build it anymore. That was specifically to build Facebook's stuff

**Comment by its-charan-here** [comment]
okay thanks!
